name: Validate front end app

on:
  push:
  pull_request:
  merge_group: 
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Build
        run: npm run build --if-present
        working-directory: ./frontend

    #   - name: Test
    #     run: npm test

      - name: Upload dist folder
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./frontend/dist